FROM debian:stable
MAINTAINER Chris Kleeschulte <chrisk@bitpay.com>
RUN useradd -d /home/debian -m -s /bin/bash debian 
WORKDIR /home/debian
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
apt-get --no-install-recommends -yq install \
git-core \
ca-certificates \
ruby \
openssh-client \
rsync \
sudo
RUN bash -c "echo '#!/bin/bash' > /home/debian/copy_keys"
RUN bash -c "echo 'cp -r /home/debian/.ssh/id_rsa* /shared/' >> /home/debian/copy_keys"
RUN bash -c "echo 'chown debian.debian /shared/id_rsa*' >> /home/debian/copy_keys"
RUN bash -c "chmod +x /home/debian/copy_keys"
RUN bash -c "echo '%debian ALL=NOPASSWD: /home/debian/copy_keys' > /etc/sudoers.d/copy_keys"
USER debian
RUN ssh-keygen -t rsa -N '' -f /home/debian/.ssh/id_rsa

