FROM ubuntu:trusty
MAINTAINER Chris Kleeschulte <chrisk@bitpay.com>
RUN useradd -d /home/ubuntu -m -s /bin/bash ubuntu
RUN mkdir -p -m0755 /var/run/sshd
RUN bash -c "mkdir -p /home/ubuntu/.ssh && \
ln -s /shared/id_rsa.pub /home/ubuntu/.ssh/authorized_keys && \
chown -R ubuntu.ubuntu /home/ubuntu/.ssh"
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
apt-get --no-install-recommends -yq install \
build-essential \
curl \
g++-multilib \
git-core \
pkg-config \
autoconf \
libtool \
automake \
faketime \
bsdmainutils \
binutils-gold \
ca-certificates \
python \
openssh-server \
rsync
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
