FROM debian:stable
MAINTAINER Chris Kleeschulte <chrisk@bitpay.com>
RUN useradd -d /home/debian -m -s /bin/bash debian 
WORKDIR /home/debian
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
apt-get --no-install-recommends -yq install \
git-core \
ca-certificates \
ruby \
openssh-client \
rsync \
sudo
RUN bash -c "echo '#!/bin/bash' > /home/debian/copy_keys"
RUN bash -c "echo 'cp -r /home/debian/.ssh/id_rsa.pub /shared/' >> /home/debian/copy_keys"
RUN bash -c "echo 'cp -r /home/debian/.ssh/id_rsa.pub /shared/root_id_rsa.pub' >> /home/debian/copy_keys"
RUN bash -c "echo 'cp -r /home/debian/.ssh/id_rsa* /home/debian/gitian-builder/var/' >> /home/debian/copy_keys"
RUN bash -c "echo 'chown debian.debian /shared/id_rsa* /home/debian/gitian-builder/var/id_rsa*' >> /home/debian/copy_keys"
RUN bash -c "chmod +x /home/debian/copy_keys"
RUN bash -c "echo '%debian ALL=NOPASSWD: /home/debian/copy_keys' > /etc/sudoers.d/copy_keys"
USER debian
RUN ssh-keygen -t rsa -N '' -f /home/debian/.ssh/id_rsa
RUN bash -c "echo \"alias ssh='ssh -oStrictHostKeyChecking=no'\" >> /home/debian/.bashrc" 
RUN bash -c "cd /home/debian"
RUN bash -c "git clone --depth 1 https://github.com/devrandom/gitian-builder" 
RUN bash -c "git clone --depth 1 https://github.com/bitpay/bitcoin" 
RUN bash -c "mkdir -p /home/debian/gitian-builder/var"
RUN bash -c "echo '#!/bin/bash' > /home/debian/runit.sh"
RUN bash -c "echo 'sudo /home/debian/copy_keys && \
ssh -fN -oExitOnForwardFailure=yes -oStrictHostKeyChecking=no ubuntu@builder -L 2223:localhost:22 && \
pushd /home/debian/gitian-builder; \
./bin/gbuild --skip-image --allow-sudo --commit bitcoin=$1 --url bitcoin=$2 ../bitcoin/contrib/gitian-descriptors/gitian-linux.yml' >> /home/debian/runit.sh" 
RUN bash -c "chmod +x /home/debian/runit.sh"
